version: '3'

services:
  backend:
    image: rinz-websocket
#    container_name: rinz-websocket-container
    build: .
    restart: always
    ports:
      - "4006-4008:3000"
    networks:
      - rinz
networks:
  rinz:
    external: true
